name: Publish docs via GitHub Pages
"on":
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.SOFERAI_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SOFERAI_BOT_PRIVATE_SIGNING_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - id: committer
        run: |
          echo "bot-name=${{ steps.generate-token.outputs.app-slug }}[bot]" >> "$GITHUB_OUTPUT"
          echo "bot-email=${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com" >> "$GITHUB_OUTPUT"
      
      - name: Set Git User
        run: git config --global user.email "${{ steps.committer.outputs.bot-email }}" && git config --global user.name "${{ steps.committer.outputs.bot-name }}"

      - name: Set Git URL
        run: git config --global url.https://${{ steps.generate-token.outputs.token }}@github.com/.insteadOf https://github.com/

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Deploy docs for dev
        run: uv run mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
